In [77]:
import pandas as pd
import numpy as np

1. ¿Qué diferencia hay entre una Serie y un DataFrame?

##### Una Serie es una estructura unidimensional mientras que un 'DataFrame' es una estructura de datos bidimensional. Las series tienen solo un índice y el 'DataFrame' índice y columnas.


2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [26]:
valores = np.random.randint(1, 10, 7)
valores

array([4, 7, 2, 2, 1, 4, 7])

In [28]:
indices = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']
indices

['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [29]:
serie = pd.Series(valores, index= indices)
serie

Lunes        4
Martes       7
Miercoles    2
Jueves       2
Viernes      1
Sábado       4
Domingo      7
dtype: int64

A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [34]:
dict = {indice: valores for indice , valores in zip(indices,valores)}
dict 


{'Lunes': 4,
 'Martes': 7,
 'Miercoles': 2,
 'Jueves': 2,
 'Viernes': 1,
 'Sábado': 4,
 'Domingo': 7}

Crea una Serie con el diccionario creado en el punto anterior.

In [35]:
serie_dict = pd.Series(dict)
serie_dict 

Lunes        4
Martes       7
Miercoles    2
Jueves       2
Viernes      1
Sábado       4
Domingo      7
dtype: int64

¿Qué forma tiene esta última Serie?

In [36]:
serie_dict.shape

(7,)

¿Qué tipo de datos tiene?

In [37]:
serie_dict.dtype

dtype('int64')

¿Qué tamaño tiene?

In [38]:
serie_dict.size

7

¿Cuáles son los índices de la Serie?

In [39]:
serie_dict.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sábado',
       'Domingo'],
      dtype='object')

¿Y los values?

In [40]:
serie_dict.values

array([4, 7, 2, 2, 1, 4, 7])

Extrae el valor para el índice "lunes"

In [41]:
serie_dict['Lunes']

4

Extrae el valor para el índice "lunes", "martes" y "miércoles".

In [48]:
serie_dict[['Lunes', 'Martes', 'Miercoles']]

Lunes        4
Martes       7
Miercoles    2
dtype: int64

Extrae el valor para el índice "lunes" y "domingo".

In [49]:
serie_dict[['Lunes', 'Domingo']]

Lunes      4
Domingo    7
dtype: int64

3. Es el turno de los DataFrames

#### Crea un array de dos dimensiones con 4 filas y 3 columnas.

In [53]:
arr = np.empty((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [58]:
df = pd.DataFrame(arr, columns=[['España', 'Francia', 'Italia']])
df 

España Francia Italia
0    0.0     0.0    0.0
1    0.0     0.0    0.0
2    0.0     0.0    0.0
3    0.0     0.0    0.0

Descarga el archivo "medallas" y carga el DataFrame.

In [75]:
df_m = pd.read_csv('medallas.csv')
df_m

Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

Usando el loc extrae todas las columnas de la fila de Tailandia.

In [6]:

tailandia = df_m.loc[]
tailandia

NameError: name 'df_m' is not defined

Usando el loc extrae todas las columnas de China e Irán.